require("devwhkang.plugins-setup")

require("devwhkang.core.options")
require("devwhkang.core.keymaps")
require("devwhkang.core.colorscheme")

require("devwhkang.plugins.comment")
require("devwhkang.plugins.nvim-tree")
require("devwhkang.plugins.lualine")
require("devwhkang.plugins.telescope")
require("devwhkang.plugins.nvim-cmp")
require("devwhkang.plugins.lsp.mason")
require("devwhkang.plugins.lsp.lspsaga")
require("devwhkang.plugins.lsp.lspconfig")
require("devwhkang.plugins.lsp.null-ls")
require("devwhkang.plugins.autopairs")
require("devwhkang.plugins.treesitter")
require("devwhkang.plugins.gitsigns")
